/*
 * generated by Xtext 2.31.0
 */
package org.flickit.dsl.editor.v2.ide;


/**
 * Use this class to register ide components.
 */
public class AssessmentKitDslIdeModule extends AbstractAssessmentKitDslIdeModule {
}
