/*
 * generated by Xtext 2.28.0
 */
package org.flickit.dsl.editor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.flickit.dsl.editor.AssessmentKitDslRuntimeModule;
import org.flickit.dsl.editor.AssessmentKitDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AssessmentKitDslIdeSetup extends AssessmentKitDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AssessmentKitDslRuntimeModule(), new AssessmentKitDslIdeModule()));
	}
	
}
