/*
 * generated by Xtext 2.28.0
 */
package org.flickit.dsl.editor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.flickit.dsl.editor.ProfileRuntimeModule;
import org.flickit.dsl.editor.ProfileStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ProfileIdeSetup extends ProfileStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ProfileRuntimeModule(), new ProfileIdeModule()));
	}
	
}
