/*
 * generated by Xtext 2.31.0
 */
package org.flickit.dsl.editor.v2.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AssessmentKitDslScopeProvider extends AbstractAssessmentKitDslScopeProvider {

}
