/*
 * generated by Xtext 2.31.0
 */
package org.flickit.dsl.editor.v2;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AssessmentKitDslRuntimeModule extends AbstractAssessmentKitDslRuntimeModule {
}
