/*
 * generated by Xtext 2.28.0
 */
package org.flickit.dsl.editor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProfileStandaloneSetup extends ProfileStandaloneSetupGenerated {

	public static void doSetup() {
		new ProfileStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
