/*
 * generated by Xtext 2.28.0
 */
package org.flickit.dsl.editor;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProfileRuntimeModule extends AbstractProfileRuntimeModule {
}
