/*
 * generated by Xtext 2.28.0
 */
package org.flickit.dsl.editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ProfileUiModule extends AbstractProfileUiModule {

	public ProfileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
