name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v**'
  pull_request:
    branches:
      - '*'

env:
  MAVEN_USERNAME: mahdirezazadeh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build with Maven
        run: mvn clean compile

  deploy-snapshot-package:
    needs: [ build ]
    name: deploy snapshot package
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Extract Maven project version
        run: echo version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_OUTPUT
        id: project

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.project.outputs.version }}
        run: |
          echo $RELEASE_VERSION

      - name: Build with Maven
        if: endsWith(steps.project.outputs.version, 'SNAPSHOT') == true
        run: mvn clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Deploy to GitHub Packages
        if: endsWith(steps.project.outputs.version, 'SNAPSHOT') == true
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}

  upload-snapshot-update-site:
    needs: [ build ]
    name: upload snapshot update site
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Extract Maven project version
        run: echo version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_OUTPUT
        id: project

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.project.outputs.version }}
        run: |
          echo $RELEASE_VERSION

      - name: Verify with Maven
        run: mvn clean verify

      - name: Copy files
        run:
          cp org.flickit.dsl.editor.v2.repository/category.xml . &&
          cp org.flickit.dsl.editor.v2.repository/target/repository/*.jar . &&
          cp -r org.flickit.dsl.editor.v2.repository/target/repository/plugins . &&
          cp -r org.flickit.dsl.editor.v2.repository/target/repository/features .

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: update-${{ steps.project.outputs.version }}
          path: |
            plugins
            features
            artifacts.jar
            content.jar
            category.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

  deploy-package:
    needs: [ build ]
    name: deploy package
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build with Maven
        run: mvn clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Deploy to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}

  upload-update-site:
#    needs: [ build ]
    name: upload update site
    runs-on: ubuntu-latest
#    if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Extract Maven project version
        run: echo version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_OUTPUT
        id: project

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.project.outputs.version }}
        run: |
          echo $RELEASE_VERSION

      - name: Verify with Maven
        run: mvn clean verify

      - name: Archive files
        run:
          cp org.flickit.dsl.editor.v2.repository/category.xml org.flickit.dsl.editor.v2.repository/target/repository/ &&
          cd org.flickit.dsl.editor.v2.repository/target/repository/ &&
          zip -r update-v${{ steps.project.outputs.version }}.zip features plugins artifacts.jar content.jar category.xml &&
          mv update-v${{ steps.project.outputs.version }}.zip ../../../

      - name: Upload archive
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: update-v${{ steps.project.outputs.version }}.zip
          token: ${{ secrets.GH_PACKAGES_TOKEN }}
          tag: v${{ steps.project.outputs.version }}
          allowUpdates: true

      - name: Readme Download Button Action
        env:
          GITHUB_USER: "mahdirezazadeh"
          REPO: "dsl-parser-temp"
          FORMAT: "zip"
          VERSION: "v${{ steps.project.outputs.version }}"
          COLOR: "blue"
          BEGIN_TAG: "<!-- BEGIN LATEST UPDATE SITE DOWNLOAD BUTTON -->"
          END_TAG: "<!-- END LATEST UPDATE SITE DOWNLOAD BUTTON -->"
        run: |
          UPDATE=$(cat README.md | perl -0777 -pe 's#(${{ env.BEGIN_TAG }})(?:.|\n)*?(${{ env.END_TAG }})#${1}\n[![Download ${{ env.FORMAT }}](https://custom-icon-badges.demolab.com/badge/-Download-${{ env.COLOR }}?style=for-the-badge&logo=download&logoColor=white "Download ${{ env.FORMAT }}")](https://github.com/${{ env.GITHUB_USER }}/${{ env.REPO }}/releases/download/${{ env.VERSION }}/update-${{ env.VERSION }}.${{ env.FORMAT }})\n${2}#g')
          echo "${UPDATE}" > README.md

      - uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          message: "Update update-site download link on README.me file"
